# params: list of input sentences from screenshot
# return the list with special characters deleted and empty string deleted from list 
def preprocessText(listOfTexts):
    DEL = ['@','…','～']
    for i in range(len(listOfTexts)):
        listOfTexts[i] = listOfTexts[i].translate({ord(i):None for i in ''.join(DEL)})
    listOfTexts = list(filter(None, listOfTexts))
    return listOfTexts

# params: filename=name of the scoring file generated by BERT, 
# params: listOfTexts is list of input sentences from screenshot after preprocess
# return dic {sentence: score}, sentence is each sentence from list, score is prediction from BERT
def readResult(filename, listOfTexts):
    dic = {}
    f = open(filename, 'r')
    for sen in listOfTexts:
        score = f.readline().split('\t')[0]
        dic[sen] = score
    f.close()
    return dic

# params: l is the list of texts after preprocess step and we want to store this list as csv
# params: destination filename for testdata, for inference with BERT
# return nothing
def writeCsv(l,filename):
    f = open(filename, 'w')
    f.write('label,x_test\n')  # python will convert \n to os.linesep
    for s in l:
        tmp = '0 '+s+'\n'
        f.write(tmp)
    f.close() 
    return

# params: l is the list of texts after preprocess step and we want to store this list as csv
# params: destination filename for testdata, for inference with AWS comprehend
# return nothing
def AWSWriteTxt(l,filename):
    f = open(filename, 'w')
    for s in l:
        tmp = s+'\n'
        f.write(tmp)
    f.close() 
    return
    
# Below are examples of how to run those functions
# test = {"text":["宝,你今天怎么没有跟我说早啊,群发没有勾上我吗,明天一定要勾上我噢",
# "爱一个人就要被你们说舔狗吗？她跟别人去酒店都是问我要的钱,难道这还不够爱我吗？",
# "宝,让他戴套,钱我出,等你不想玩了我跟你结婚","",
# "今天晚上有点冷,本来以为街上没有人,结果刚刚偷电瓶的时候被抓,本来想反抗,结果警察说了一句老实点别动,我立刻就放弃了抵抗,因为我记得你说过你喜欢老实人",
# "今天下雨了,你跟她出门的时候记得要带伞,多穿一点衣服,玫瑰花扎手,拿的时候,注意不要被扎到了,亲嘴的时候记得要看一下她的健康码呀！宝贝,呜呜呜",
# "我跟朋友约好了,没办法陪你","男人都忘不了初恋的","不是因为她,只是我们之间的感情淡了","之前没觉得,慢慢的发现我们真的不合适",
# "最近真的很忙,没时间看手机",""]}

# listOfTexts = preprocessText(test["text"])
# print(listOfTexts)
# writeCsv(listOfTexts,'exam.csv')
# scores = readResult('read.csv', listOfTexts)
# print(scores)